version: 2
updates:
  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "cron"
      time: "0 * * * *"
    open-pull-requests-limit: 100
    commit-message:
      prefix: "chore"
      include: "scope"

  # Gradle Dependencies
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "cron"
      time: "0 * * * *"
    open-pull-requests-limit: 100
    commit-message:
      prefix: "chore"
      include: "scope"
