name: Renovate (Updates Gradle & GitHub Actions)

on:
  push:
    branches:
      - master
  schedule:
    - cron: "0 * * * *"   # Hourly
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.2

      - name: Run Renovate
        uses: renovatebot/github-action@v46.1.11
        with:
          token: ${{ secrets.GH_TOKEN }}
